name: Commit Test Build

on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
              board:
                - ttgo-lora32-v21
                - heltec-lora32-v2
                - heltec_wifi_lora_32_V3
                - heltec_wireless_stick
                - heltec_wireless_stick_lite_v3
                - heltec_ht-ct62
                - ESP32_DIY_LoRa
                - ESP32_DIY_1W_LoRa
                - ttgo-t-beam-v1_2
                - ttgo-t-beam-v1
                - ttgo-t-beam-v1_SX1268
                - ttgo-t-beam-v1_2_SX1262
                - ESP32_DIY_LoRa_A7670
                - heltec_wireless_tracker
                - OE5HWN_MeshCom
                - WEMOS-LOLIN32-OLED-DIY
                - WEMOS-D1-R32-RA02
                - ttgo-lora32-v21-915
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install PlatformIO Core
              run: pip install --upgrade platformio

            - name: Build target
              run: pio run -e ${{ matrix.board }}

            - name: Build FS
              run: pio run --target buildfs -e ${{ matrix.board }}